### ISSUE TITLE
Homepage content types

### ISSUE THREAD

**Issue by kirsten** [luncheonette/the-sunview#2]
Looking over the comps posted in https://github.com/luncheonette/the-sunview/issues/1 (as well as the current http://thesunview.org), I see 3 types of content:

1. Member-run events at the Sunview - music, screenings, etc. I think this also includes SLSCR stuff.
2. Announcements/info about other Sunview-related things that aren't tied to an event - CSA info, Small Business Jobs Survival Act.
3. Images

My interpretation of what was in the comp was that:

- The "What has or hasn't happened here"/Sunview members section is meant to be a list of member-run events that actually happened in the space. Are these supposed to be past events? Upcoming? Both?
- The grid of images/posts toward the top seems like a mixture of all 3 types of content mentioned above. Is this content just a mix of the most recently added stuff, or should it be more curated? It would be easy to add some kind of flag for whether or not to display content on the homepage...

I haven't added any custom collections in Jekyll yet, though it seems like things might head in that direction. Wanted to hold off on that until I have a better understanding of what content we expect to add/how it's going to be used.

**Comment by dgoats** [comment]
Hi! Wow, impressive! Here are a few initial thoughts on your initial questions:

1: Exactly!  I think here we might want some kind of category so we can reassemble these into "collections" - like all the SLSCR events to appear on a single SLSCR page.
2: Exactly. It's looking great how you have it, I think. A few comments below about how to sort them.
3: Images - These are sweet.  These could also be linkable, possibly to external links?  But not forcibly, it's nice to have some elements that are just floating signifiers and don't necessarily lead anywhere.

4: I think these were intended to be upcoming and past events.  Similar to this page:
http://thesunview.org/menu/  
- Could this be a scrollable block (or infinite scroll/AJAX load) so we can list all events right on that homepage? 
- The language header can be simplified (see my issue #3),  I suppose a better title is just: "What's happening..."

5: Good question.  I think a flag would be helpful.  It might be nice for us to be able to reorder these in some easy fashion - the CSA can be top news when they're looking for people to sign up, for example, but at other times we could move it down the page.  Since the top image fills the frame on mobile it seems like being able to hide and/or reorder would be key.

A couple new questions for you:

6: What are custom collections, exactly?  Is that like what I was mentioning above with SLSCR-related posts, etc?

7: Will we have a menu of some kind someplace?  

8: I hadn't thought of this, but we need a place for locations images, as in: http://www.thesunview.org/locations.  & it's nice to be able to send potential renters to a static link rather than having them scroll down a page, etc.  We might need some other areas for static content that we don't necessarily want to have come up as a big image on the homepage/header like those other announcements.  Things like: http://thesunview.org/henry-st-tool-library-and-exchange/  and a "History" or "About" page.

What's the best way to handle these things (locations page, tool library, risograph page)?

**Comment by kirsten** [comment]
Thanks Dylan, and sorry for the slow follow-up!

> 1: Exactly! I think here we might want some kind of category so we can reassemble these into "collections" - like all the SLSCR events to appear on a single SLSCR page.

Yep! I think that would be easy to do using tags or categories. If all the SLSCR posts were categorized "SLSCR", I could create a special page that just displayed all those events.

> 3: Images - These are sweet. These could also be linkable, possibly to external links? But not forcibly, it's nice to have some elements that are just floating signifiers and don't necessarily lead anywhere.

These could optionally have links associated with them. Maybe I'll start without links and if we have a need for them I can definitely add.

> 6: What are custom collections, exactly? Is that like what I was mentioning above with SLSCR-related posts, etc?

Collections are things you can create in Jekyll when you have a bunch of documents that aren't regular posts or pages (https://jekyllrb.com/docs/collections/). E.g. I created a custom collection of "releases" for the Jantar website, so I could keep track of things like release date, record label, album title, etc. in a structured way. Not sure yet if we need them or where!

> 7: Will we have a menu of some kind someplace?

Yes, we should! Especially as we add more pages (history, location, slsrc, etc.) people will need a way to navigate around. I'll open a new issue for this to keep track.

> 8: I hadn't thought of this, but we need a place for locations images, as in: http://www.thesunview.org/locations. & it's nice to be able to send potential renters to a static link rather than having them scroll down a page, etc. We might need some other areas for static content that we don't necessarily want to have come up as a big image on the homepage/header like those other announcements. Things like: http://thesunview.org/henry-st-tool-library-and-exchange/ and a "History" or "About" page.

> What's the best way to handle these things (locations page, tool library, risograph page)?

Yeah, I assumed we'd need static pages for this stuff as well. I can create separate pages for things like rentals, history, etc. - we wouldn't want them to become part of the content that feeds into the homepage. I'll make a separate issue for identifying/creating these pages.
